version: "3.8"

services:
  gsky_ows:
    image: eahazardswatch.icpac.net/gsky-ows:latest
    container_name: gsky_ows
    build:
      context: ./ows
      args:
        gsky_repo: ${GSKY_REPO}
        gsky_branch: ${GSKY_BRANCH}
    restart: ${RESTART_POLICY}
    volumes:
      - ${GSKY_CONFIG_FOLDER}:/gsky/etc
    environment: 
      - OWS_HOSTNAME=eahazardswatch.icpac.net/gsky
      - OWS_PROTOCOL=http
      - MAS_ADDRESS=gsky_mas_api:8888
      - WORKER_NODES="gsky_rpc_1:6000","gsky_rpc_2:6000"
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - WEBHOOK_ENABLED=true
    ports:
      - 8080:8080
  gsky_mas_db:
    image: postgis/postgis:12-master
    container_name: gsky_mas_db
    volumes:
        - gsky_mas_db:/var/lib/postgresql
    ports:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mas
  gsky_mas_api:
    image: eahazardswatch.icpac.net/gsky-mas:latest
    container_name: gsky_mas_api
    build:
      context: ./mas_api
      args:
        gsky_repo: ${GSKY_REPO}
        gsky_branch: ${GSKY_BRANCH}
    restart: ${RESTART_POLICY}
    volumes:
      - ./data:/gskydata
      - ./mas_api/scripts/ingest.sh:/ingest.sh
    environment:
      - WAIT_HOSTS=gsky_mas_db:5432
      - WAIT_TIMEOUT=120
      - PGHOST=gsky_mas_db
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDB=mas
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - WEBHOOK_ENABLED=true
    ports:
      - 8888:8888
  gsky_rpc_1:
    image: eahazardswatch.icpac.net/gsky-rpc:latest
    container_name: gsky_rpc_1
    build:
      context: ./rpc
      args:
        gsky_repo: ${GSKY_REPO}
        gsky_branch: ${GSKY_BRANCH}
    restart: ${RESTART_POLICY}
    volumes:
      - ./data:/gskydata
    environment:
      - WAIT_HOSTS=gsky_mas_db:5432
      - WAIT_TIMEOUT=120
    ports:
      - 6000
  gsky_rpc_2:
      image: eahazardswatch.icpac.net/gsky-rpc:latest
      container_name: gsky_rpc_2
      build:
        context: ./rpc
        args:
          gsky_repo: ${GSKY_REPO}
          gsky_branch: ${GSKY_BRANCH}
      restart: ${RESTART_POLICY}
      volumes:
        - ./data:/gskydata
      environment:
        - WAIT_HOSTS=gsky_mas_db:5432
        - WAIT_TIMEOUT=120
      ports:
        - 6000
volumes:
  gsky_mas_db: