services:
  gsky_mas_api:
    build:
      args:
        gsky_branch: ${GSKY_BRANCH}
        gsky_repo: ${GSKY_REPO}
      context: ./mas_api
    container_name: gsky_mas_api
    environment:
    - WAIT_HOSTS=gsky_mas_db:5432
    - WAIT_TIMEOUT=120
    - PGHOST=gsky_mas_db
    - PGPORT=5432
    - PGUSER=postgres
    - PGPASSWORD=${POSTGRES_PASSWORD}
    - PGDB=mas
    - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    - WEBHOOK_ENABLED=true
    image: eahazardswatch.icpac.net/gsky-mas:latest
    ports:
    - 8888
    - 9000
    restart: ${RESTART_POLICY}
    volumes:
    - ${GSKY_DATA_FOLDER}:/gskydata
    - ./mas_api/scripts/ingest.sh:/ingest.sh
    - ./ingest_scripts:/ingest_scripts
    - ./ows/rulesets:/rulesets
    - ./webhooks/mas-hooks.yaml:/hooks.yaml
  gsky_mas_db:
    container_name: gsky_mas_db
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=mas
    image: postgis/postgis:12-master
    ports:
    - 5455:5432
    restart: ${RESTART_POLICY}
    volumes:
    - gsky_mas_db:/var/lib/postgresql
  gsky_memcached:
    container_name: gsky_memcached
    image: memcached:1.6.12-alpine
    ports:
    - 11211
    restart: ${RESTART_POLICY}
  gsky_nginx:
    build:
      context: ./nginx
    command: sh -c "/wait && nginx -g 'daemon off;'"
    container_name: gsky_nginx_proxy
    environment:
    - WAIT_HOSTS=gsky_ows:8080, gsky_mas_api:8888, gsky_wps_client:3000
    - WAIT_TIMEOUT=120
    image: eahazardswatch.icpac.net/gsky-nginx:latest
    ports:
    - ${NGINX_PUBLIC_PORT}:80
    restart: ${RESTART_POLICY}
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  gsky_ows:
    build:
      args:
        gsky_branch: ${GSKY_BRANCH}
        gsky_repo: ${GSKY_REPO}
      context: ./ows
    container_name: gsky_ows
    environment:
    - WAIT_HOSTS=gsky_mas_db:5432, gsky_rpc_1:6000, gsky_rpc_2:6000, gsky_rpc_3:6000,
      gsky_rpc_4:6000
    - WAIT_TIMEOUT=120
    - OWS_HOSTNAME=${GSKY_OWS_HOSTNAME}
    - OWS_PROTOCOL=${GSKY_OWS_PROTOCOL}
    - MAS_ADDRESS=gsky_mas_api:8888
    - WORKER_NODES="gsky_rpc_1:6000","gsky_rpc_2:6000","gsky_rpc_3:6000","gsky_rpc_4:6000"
    - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    - WEBHOOK_ENABLED=true
    - MEMCACHE_URI=gsky_memcached:11211
    image: eahazardswatch.icpac.net/gsky-ows:latest
    ports:
    - 8080
    - 9000
    restart: ${RESTART_POLICY}
    volumes:
    - ${GSKY_CONFIG_FOLDER}:/gsky/etc
    - ./ows/templates/WMS_GetCapabilities.tpl:/gsky/share/gsky/templates/WMS_GetCapabilities.tpl
    - ./ows/templates/WPS_GetCapabilities.tpl:/gsky/share/gsky/templates/WPS_GetCapabilities.tpl
    - ./ows/templates/WCS_GetCapabilities.tpl:/gsky/share/gsky/templates/WCS_GetCapabilities.tpl
    - ./ows/templates/WPS:/templates/WPS
    - ./ows/rulesets:/rulesets
  gsky_rpc_1:
    build: &id001
      args:
        gsky_branch: ${GSKY_BRANCH}
        gsky_repo: ${GSKY_REPO}
      context: ./rpc
    container_name: gsky_rpc_1
    environment: &id002
    - WAIT_HOSTS=gsky_mas_db:5432
    - WAIT_TIMEOUT=120
    image: eahazardswatch.icpac.net/gsky-rpc:latest
    ports: &id003
    - 6000
    restart: ${RESTART_POLICY}
    volumes: &id004
    - ${GSKY_DATA_FOLDER}:/gskydata
  gsky_rpc_2:
    build: *id001
    container_name: gsky_rpc_1
    environment: *id002
    image: eahazardswatch.icpac.net/gsky-rpc:latest
    ports: *id003
    restart: ${RESTART_POLICY}
    volumes: *id004
  gsky_rpc_3:
    build: *id001
    container_name: gsky_rpc_1
    environment: *id002
    image: eahazardswatch.icpac.net/gsky-rpc:latest
    ports: *id003
    restart: ${RESTART_POLICY}
    volumes: *id004
  gsky_rpc_4:
    build: *id001
    container_name: gsky_rpc_1
    environment: *id002
    image: eahazardswatch.icpac.net/gsky-rpc:latest
    ports: *id003
    restart: ${RESTART_POLICY}
    volumes: *id004
version: '3.8'
volumes:
  gsky_mas_db: null
